version: "2.13.0"
services:
  web:
    build: .

    command: python app.py 0.0.0.0:8000
    volumes:
      - .:/code 
    ports:
      - "8000:8000"   
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    ports:
      - "5432:5432"
    restart: always    

volumes:
  postgres_data:
